# Generated by Django 3.2.3 on 2021-05-23 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_auto_20210521_1734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
