# Generated by Django 3.2.3 on 2021-05-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_auto_20210523_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_text',
        ),
    ]
